CLASS z_class_la DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS z_class_la IMPLEMENTATION.
METHOD IF_OO_ADT_CLASSRUN~MAIN.
out->write( 'Hello world' ).
ENDMETHOD.
ENDCLASS.
